services:
  - type: web
    name: aurelis-wear-shop-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: aurelis-wear-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: FRONTEND_URL
        value: "https://aurelis-wear-shop.vercel.app"

databases:
  - name: aurelis-wear-db
    plan: free